fix(docker): File permissions
Running this Docker image in Kubernetes with an unprivileged user results in the following error:
```sh
PermissionError: [Errno 13] Permission denied: '/home/app/gunicorn_conf.py'
```
This is because the `app` user didn't have execute permissions for `gunicorn_conf.py`
```sh
ls -l
drwxr-xr-x 9 root root 4096 Feb 20 02:45 app
-rw-r----- 1 root root 2268 Feb 20 02:45 gunicorn_conf.py
```